pipeline {
    agent any

    tools {
        maven 'M3' // This assumes you've configured Maven in Jenkins as 'M3'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/zakirujjan/Hello-World.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("hello-world:latest")
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    docker.image("hello-world:latest").inside {
                        sh 'java -jar /usr/local/lib/hello-world.jar'
                    }
                }
            }
        }
    }
}

